name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run format:check
      - run: npm run test
      - name: Apply yamllint
        run: |
          sudo pip install yamllint
          yamllint --strict .github/workflows

  benchmark:
    name: Run benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - name: Save previous data.js
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          cp ./dev/bench/data.js before_data.js
          git checkout -
      - name: Run benchmark
        run: cd example && node bench.js | tee output.json
      - name: Store benchmark result
        uses: ./
        with:
          name: Example Benchmark
          tool: 'customSmallerIsBetter'
          output-file-path: example/output.json
          fail-on-alert: true
      - run: node ./dist/scripts/ci_validate_modification.js before_data.js 'Example Benchmark'

  only-alert-with-cache:
    name: Run alert check with actions/cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - name: Run benchmark
        run: cd example && node bench.js | tee output.json
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-ci-cache-test
      - name: Store benchmark result
        uses: ./
        with:
          name: Alert setup example with cache
          tool: 'customSmallerIsBetter'
          output-file-path: example/output.json
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@scheibo'
